version: '3.9'

services:
    app:
        container_name: flask
        build: .
        ports:
            - "8000:5000"   # Flask debug server
            - "8080:80"     # Flask apache server
        volumes:
            - .:/app
